# Generated by Django 4.2.6 on 2023-11-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_description',
            new_name='Ingredients',
        ),
    ]
